# Generated by Django 4.2.15 on 2025-03-25 18:45

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quillpost',
            name='more_content',
            field=django_quill.fields.QuillField(default=''),
            preserve_default=False,
        ),
    ]
